### ISSUE TITLE
export checkboxes don't get recalled properly

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#91]
For example I go through the videos 1-by-1 and check to render all videos, and then some of them will have the vids, others just the pics. Probably an issue related to [menubar].

**Comment by aleksati** [comment]
Strange. I just managed to pull, create a build and do two tests on a number of videos. Seems to export just fine on my Mac.

**Comment by balintlaczko** [comment]
Seems to be OK now, but I just keep this open for a while and we can close it if we haven't seen it happening for a longer time.

**Comment by balintlaczko** [comment]
OK, localized the problem now. So they work okay normally, they save normally, but when you recall a settings file, (or just an item via the umenu) it does not recall what you set, and actually overwrites your data. Something around [VA_export_boxes_data].

**Comment by aleksati** [comment]
Yes, it actually overwrote the dict VA_item every time it recalled export options. This can be fixed with a separate send from the menubar to the [VA_export_boxes_data] which only receives data when you actively change an export option in the menubar, not when something is recalled.

**Comment by aleksati** [comment]
I just pushed these minor changes to the [Menubar] and [VA_export_boxes_data] now, they´re colored in purple so you know what I changed. Is this what you meant was causing the problem?

**Comment by balintlaczko** [comment]
Still not working with recalling a settings json, and the reason why is that all the [coll]-s in [VA_export_boxes_data] are empty at that time (after loading a video folder and a settings.json). We could further tweak that it first extracts the value from the dict and save it in the coll and then sending it from the coll, but this seems to be a bit convoluted for me. If we save everything into a dict already there should be very few reasons to save things to a coll as well. I will try to think about a simpler, dict-based approach now.
